### ISSUE TITLE
Do we use secondary calibration in femto?

### ISSUE THREAD

**Issue by stephf0716** [slaclab/femto-timing#3]
What is the secondary calibration and do we use it?

https://github.com/slaclab/femto-timing/blob/18712e9a3ac6ea6dcb747b418bf2c1007c0192b7/exp-timing/femto.py#L443-L447

**Comment by rlodico06** [comment]
use_secondary_calibration is currently set to false for all of the laser lockers. Since this feature is not useful for our LCLS-I laser lockers, we should consider removing it as part of the OIP.

**Comment by rlodico06** [comment]
If we do remove the secondary calibration feature, we would also remove the secondary_calibration_enable, secondary_calibration, secondary_calibration_s, and secondary_calibration_c dictionaries.

**Comment by rlodico06** [comment]
t0, which is an array of phase shift times, is defined in the secondary calibration function and later used in the Sawtooth function, which is critical to the script. If the secondary calibration is ultimately removed, t0 will need to be defined elsewhere to preserve sawtooth functionality.
